// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZT-8kMjNYqR4qA4m9VyCTzbcv37s-6go',
    appId: '1:163752744140:web:7afc7a9310c4e60b781e69',
    messagingSenderId: '163752744140',
    projectId: 'minik-app-bc154',
    authDomain: 'minik-app-bc154.firebaseapp.com',
    storageBucket: 'minik-app-bc154.firebasestorage.app',
    measurementId: 'G-36SG3WGPHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTd0l694vZO5L72geJp5GzBDc_E7K_x_U',
    appId: '1:163752744140:android:4dd3393ec27f4d69781e69',
    messagingSenderId: '163752744140',
    projectId: 'minik-app-bc154',
    storageBucket: 'minik-app-bc154.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVmY9CSxriqjhD7K_UbqcZPf6S2NVXtc',
    appId: '1:163752744140:ios:7442532c3936c585781e69',
    messagingSenderId: '163752744140',
    projectId: 'minik-app-bc154',
    storageBucket: 'minik-app-bc154.firebasestorage.app',
    iosBundleId: 'com.example.minikAppTania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVmY9CSxriqjhD7K_UbqcZPf6S2NVXtc',
    appId: '1:163752744140:ios:7442532c3936c585781e69',
    messagingSenderId: '163752744140',
    projectId: 'minik-app-bc154',
    storageBucket: 'minik-app-bc154.firebasestorage.app',
    iosBundleId: 'com.example.minikAppTania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZT-8kMjNYqR4qA4m9VyCTzbcv37s-6go',
    appId: '1:163752744140:web:a54cecd96c24f8eb781e69',
    messagingSenderId: '163752744140',
    projectId: 'minik-app-bc154',
    authDomain: 'minik-app-bc154.firebaseapp.com',
    storageBucket: 'minik-app-bc154.firebasestorage.app',
    measurementId: 'G-9D6HMBVXRK',
  );
}
